--- !ditz.rubyforge.org,2008-03-06/project 
name: zoob
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: zoob
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: android market
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-05-02 13:21:20.357320 Z
    - Julien Rebetez <julien@fhtagn.net>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: post-market
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-05-20 13:16:03.154211 Z
    - Julien Rebetez <julien@fhtagn.net>
    - created
    - ""
